### ISSUE TITLE
councilmatic.org has expired HTTPS/SSL certificate

### ISSUE THREAD

**Issue by skorasaurus** [datamade/councilmatic-splash#9]
Hi, 

In case you weren't aware, councilmatic.org has an expired certificate.

**Comment by jeancochrane** [comment]
Thanks for reporting this @skorasaurus. Somehow the rate limit of 25 certs issued per week has been breached for the domain `www.councilmatic.org`. This strikes me as pretty strange because we only have one cert for this domain on the server and it was last renewed in January, but you can see on crt.sh that there are indeed a bunch of duplicate certs for `www.councilmatic.org` getting issued every week: https://crt.sh/?q=www.councilmatic.org.

This doesn't ring a bell at all, does it @hancush? I'm not totally sure how certs are provisioned for the Councilmatic sites, and whether or not I should expect anything out of the ordinary. If not, I'll have to do some digging to track down where these duplicate certs are getting requested from.

**Comment by hancush** [comment]
@jeancochrane i’m not sure what’s going on. there were problems with this cert a few months ago: https://github.com/datamade/devops/issues/63 (private link)

also, i’m not sure how the splash site is managed (i.e., deployed) these days. @derekeder do you have some insight here?

since it has been a continued source of issues, if it’s still using the deprecated webhook or something else non-standard, i would advocate for bringing it in line with our current sop and migrating it to netlify.

**Comment by derekeder** [comment]
@hancush agreed, let's bring it over to Netlify. I have access to the DNS whenever we make the change. I would flag this as high priority as the site is down due to this.

**Comment by jeancochrane** [comment]
I'd like to bring it over to Netlify too, but I'm worried that won't fix the root problem. Netlify uses LE for SSL under the hood too, and if this rate limit applies globally to the `www.councilmatic.org` domain (as the error messages indicate), Netlify may not be able to provision the certificate either. It's worth a shot, but we should be prepared to try to dig deeper on where and why there are so many dupllicate certs being provisioned.
